### ISSUE TITLE
Pull request?

### ISSUE THREAD

**Issue by arctouch-thiagoporciuncula** [romeirao/ArcTouchTest#1]
Hi @romeirao,

Could you please open a pull request with all your code to a clean branch? This would make our evaluation simpler, as we'd be able to add comments to specific parts of your code in the pull request.

Also, this is the step 5 of the Code Test :)

Thanks.

**Comment by romeirao** [comment]
Hi @arctouch-thiagoporciuncula Sorry, my bad. It is already there.
